## 1. Understanding Data

In [1]:
import os
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings(action='ignore')#에러메세지 제거

### Load data

In [2]:
train = pd.read_csv('train.csv')
test  = pd.read_csv('test.csv')

In [3]:
train.head()

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0,40,Private,168538,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,United-States,>50K
1,1,17,Private,101626,9th,5,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,20,United-States,<=50K
2,2,18,Private,353358,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,16,United-States,<=50K
3,3,21,Private,151158,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,25,United-States,<=50K
4,4,24,Private,122234,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,20,?,<=50K

In [4]:
### 데이터 확인

* id
* age : 나이
* workclass : 고용 형태
* fnlwgt : 사람 대표성을 나타내는 가중치 (final weight의 약자)
* education : 교육 수준
* education_num : 교육 수준 수치
* marital_status: 결혼 상태
* occupation : 업종
* relationship : 가족 관계
* race : 인종
* sex : 성별
* capital_gain : 양도 소득
* capital_loss : 양도 손실
* hours_per_week : 주당 근무 시간
* native_country : 국적
* income : 수익 (예측해야 하는 값)
    * \>50K : 1
    * <=50K : 0

### Pandas 라이브러리

loc, iloc, info, describe, value_counts, head, tail, sample, map, apply, groupby 등

In [5]:
train.sample(10)

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
17525,17525,20,Local-gov,188950,Some-college,10,Never-married,Protective-serv,Own-child,White,Male,0,0,25,United-States,<=50K
12903,12903,47,Self-emp-inc,127678,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,80,United-States,<=50K
21754,21754,66,Private,178120,5th-6th,3,Divorced,Priv-house-serv,Not-in-family,Black,Female,0,0,15,United-States,<=50K
2424,2424,22,Private,190968,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
12952,12952,23,Private,201138,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,8,United-States,<=50K
14095,14095,31,Private,283268,Bachelors,13,Never-married,Prof-specialty,Unmarried,White,Female,0,0,36,United-States,<=50K
14684,14684,33,Private,309630,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
19631,19631,51,Private,410114,Masters,14,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
19817,19817,52,Private,138944,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
2042,2042,42,Local-gov,267252,Masters,14,Separated,Exec-managerial,Unmarried,Black,Male,0,0,45,United-States,>50K

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26049 entries, 0 to 26048
Data columns (total 16 columns):
id                26049 non-null int64
age               26049 non-null int64
workclass         26049 non-null object
fnlwgt            26049 non-null int64
education         26049 non-null object
education_num     26049 non-null int64
marital_status    26049 non-null object
occupation        26049 non-null object
relationship      26049 non-null object
race              26049 non-null object
sex               26049 non-null object
capital_gain      26049 non-null int64
capital_loss      26049 non-null int64
hours_per_week    26049 non-null int64
native_country    26049 non-null object
income            26049 non-null object
dtypes: int64(7), object(9)
memory usage: 3.2+ MB

In [7]:
train.describe()

,id,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,26049.000000,26049.000000,2.604900e+04,26049.000000,26049.00000,26049.000000,26049.000000
mean,13024.000000,38.569235,1.903045e+05,10.088372,1087.68970,87.732734,40.443126
std,7519.842917,13.671489,1.059663e+05,2.567610,7388.85469,403.230205,12.361850
min,0.000000,17.000000,1.376900e+04,1.000000,0.00000,0.000000,1.000000
25%,6512.000000,28.000000,1.181080e+05,9.000000,0.00000,0.000000,40.000000
50%,13024.000000,37.000000,1.788660e+05,10.000000,0.00000,0.000000,40.000000
75%,19536.000000,48.000000,2.377350e+05,12.000000,0.00000,0.000000,45.000000
max,26048.000000,90.000000,1.484705e+06,16.000000,99999.00000,4356.000000,99.000000

In [8]:
train.native_country.value_counts()

United-States                 23371
Mexico                          534
?                               456
Philippines                     163
Germany                         101
Puerto-Rico                      95
Canada                           92
El-Salvador                      79
India                            77
Cuba                             76
England                          67
Jamaica                          64
South                            63
China                            57
Guatemala                        52
Columbia                         52
Italy                            50
Vietnam                          50
Dominican-Republic               48
Japan                            47
Poland                           47
Taiwan                           39
Iran                             35
Haiti                            35
Portugal                         30
Nicaragua                        28
Peru                             26
Greece                           24
Ecuador                          24
France                           24
Ireland                          18
Laos                             15
Cambodia                         14
Hong                             14
Trinadad&Tobago                  14
Outlying-US(Guam-USVI-etc)       13
Thailand                         13
Yugoslavia                       12
Hungary                          11
Honduras                         11
Scotland                          8
Name: native_country, dtype: int64

In [9]:
type(train['native_country'])

pandas.core.series.Series

type(train)
>dataframe

type(train.native_country)

type(train['native_country'])
>series

데이터 프레임과 시리스는 쓸 수 있는 함수가 다르다.
따라서 쓰고있는 함수의 종류를 잘 파악해놓아야 한다.

In [10]:
train.capital_gain.describe(percentiles=[.99])
#()안에서 shift+tap을 계속 누르면 힌트가 나옴

count    26049.00000
mean      1087.68970
std       7388.85469
min          0.00000
50%          0.00000
99%      15024.00000
max      99999.00000
Name: capital_gain, dtype: float64

In [11]:
train.loc[train.capital_gain ==99999, :]
#loc,iloc
#capital_gain의 99999값 나열
#iloc는 colum의 형태가 정수형으로 표현되므로 숫자로 씀

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
227,227,24,?,151153,Some-college,10,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,99999,0,50,South,>50K
430,430,55,Private,408537,9th,5,Divorced,Craft-repair,Unmarried,White,Female,99999,0,37,United-States,>50K
848,848,32,Private,330715,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K
852,852,66,Private,115498,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,55,?,>50K
1209,1209,37,Local-gov,287306,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Wife,Black,Female,99999,0,40,?,>50K
1310,1310,56,Self-emp-inc,98418,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,40,United-States,>50K
1330,1330,47,Private,181307,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,99999,0,60,United-States,>50K
1470,1470,33,Private,162572,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,40,United-States,>50K
1473,1473,51,Private,145714,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,?,>50K
1571,1571,54,Self-emp-not-inc,269068,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99999,0,50,Philippines,>50K
1887,1887,50,Self-emp-not-inc,155118,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Female,99999,0,35,United-States,>50K
1925,1925,41,Self-emp-inc,194636,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,99999,0,65,United-States,>50K
2101,2101,40,Local-gov,150755,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,75,United-States,>50K
2123,2123,53,Private,88842,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,40,United-States,>50K
2478,2478,43,Private,462180,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,60,United-States,>50K
3038,3038,46,Private,370119,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,60,United-States,>50K
3832,3832,41,Self-emp-inc,495061,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,70,United-States,>50K
4604,4604,36,Self-emp-not-inc,241998,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,99999,0,20,United-States,>50K
4678,4678,43,Self-emp-inc,172826,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,99999,0,55,United-States,>50K
4748,4748,49,Self-emp-inc,362795,Masters,14,Divorced,Prof-specialty,Unmarried,White,Male,99999,0,80,Mexico,>50K
4896,4896,40,Self-emp-not-inc,204235,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
5196,5196,21,Private,334618,Some-college,10,Never-married,Protective-serv,Not-in-family,Black,Female,99999,0,40,United-States,>50K
5456,5456,39,Private,190297,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,55,United-States,>50K
5478,5478,38,Private,146091,Doctorate,16,Married-civ-spouse,Exec-managerial,Wife,White,Female,99999,0,36,United-States,>50K
6109,6109,56,Self-emp-inc,205601,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,70,United-States,>50K
6221,6221,59,Self-emp-not-inc,165315,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,43,United-States,>50K
6264,6264,47,Private,193047,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
6585,6585,57,Self-emp-not-inc,95280,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,99999,0,45,United-States,>50K
6613,6613,40,Private,79586,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99999,0,40,?,>50K
6633,6633,71,Self-emp-inc,38822,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20752,20752,50,Self-emp-not-inc,401118,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,50,United-States,>50K
20926,20926,42,Local-gov,175642,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Female,99999,0,40,United-States,>50K
21201,21201,42,Self-emp-not-inc,201908,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,50,United-States,>50K
21484,21484,52,Self-emp-inc,90363,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,35,United-States,>50K
21488,21488,65,Private,105491,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,40,United-States,>50K
21512,21512,46,Private,273771,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,99999,0,40,United-States,>50K
21542,21542,47,Private,155664,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,55,United-States,>50K
22006,22006,44,Private,332401,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,65,United-States,>50K
22299,22299,50,Private,183173,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,40,United-States,>50K
22494,22494,33,Private,134886,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,99999,0,30,United-States,>50K
22563,22563,42,Local-gov,180985,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,99999,0,40,United-States,>50K
22816,22816,30,Private,132601,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
22894,22894,37,Self-emp-not-inc,353298,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,99999,0,50,United-States,>50K
22980,22980,47,Private,102308,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
23030,23030,52,Self-emp-inc,181855,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Other,Male,99999,0,65,United-States,>50K
23083,23083,74,Private,188709,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,50,United-States,>50K
23121,23121,56,Self-emp-not-inc,163212,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,99999,0,40,United-States,>50K
23573,23573,55,Self-emp-inc,392325,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,99999,0,60,United-States,>50K
24041,24041,52,Self-emp-not-inc,140985,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,99999,0,30,United-States,>50K
24195,24195,36,Private,383518,Some-college,10,Married-civ-spouse,Adm-clerical,Wife,Black,Female,99999,0,40,United-States,>50K
24267,24267,31,Private,100252,Bachelors,13,Divorced,Other-service,Not-in-family,Asian-Pac-Islander,Male,99999,0,70,United-States,>50K
24654,24654,58,?,266792,Some-college,10,Married-civ-spouse,?,Husband,White,Male,99999,0,40,United-States,>50K
24779,24779,39,Private,77005,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,40,United-States,>50K
24976,24976,48,Private,25468,Masters,14,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,50,United-States,>50K
25134,25134,49,Private,159816,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,White,Female,99999,0,20,United-States,>50K
25535,25535,55,Private,197399,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,55,United-States,>50K
25648,25648,64,Self-emp-inc,185912,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,35,United-States,>50K
25705,25705,41,Private,115932,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
25824,25824,50,Self-emp-not-inc,132716,Prof-school,15,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,50,United-States,>50K
25987,25987,63,Private,118798,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K

In [12]:
train.capital_gain < 99999

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
         ...
26019    True
26020    True
26021    True
26022    True
26023    True
26024    True
26025    True
26026    True
26027    True
26028    True
26029    True
26030    True
26031    True
26032    True
26033    True
26034    True
26035    True
26036    True
26037    True
26038    True
26039    True
26040    True
26041    True
26042    True
26043    True
26044    True
26045    True
26046    True
26047    True
26048    True
Name: capital_gain, Length: 26049, dtype: bool

In [13]:
train.capital_gain < 99999

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
         ...
26019    True
26020    True
26021    True
26022    True
26023    True
26024    True
26025    True
26026    True
26027    True
26028    True
26029    True
26030    True
26031    True
26032    True
26033    True
26034    True
26035    True
26036    True
26037    True
26038    True
26039    True
26040    True
26041    True
26042    True
26043    True
26044    True
26045    True
26046    True
26047    True
26048    True
Name: capital_gain, Length: 26049, dtype: bool

In [14]:
train.income= train.income.map(lambda x:int(x=='>50K'))
# map series함수,자료를 변형시킨다.새로운 series를 불러옴 
# lambda하나하나의 tuple,list를 의미함 
# == true(1) or false(0)
# =으로 지정해주어야 함

In [15]:
train.shape

(26049, 16)

In [16]:
train.apply(lambda x:x['age']+ x['hours_per_week'],axis=1)
#axis=0;(26049),axis=1;(16) from train.shape
#x의 축을 어느 기준으로 잡을 것인지

0        100
1         37
2         34
3         46
4         44
5         83
6         93
7         77
8        107
9        106
10        74
11        56
12        84
13        38
14        85
15        79
16        77
17        94
18        95
19        79
20        26
21        89
22       125
23        65
24       113
25        71
26       102
27        61
28        86
29        63
        ...
26019     82
26020     63
26021     59
26022     67
26023     76
26024     78
26025     47
26026     79
26027    115
26028     70
26029     72
26030     78
26031     82
26032     75
26033     79
26034     86
26035     70
26036     84
26037     70
26038     81
26039     92
26040     79
26041     84
26042     98
26043     82
26044    109
26045     63
26046     93
26047     66
26048     50
Length: 26049, dtype: int64

In [17]:
train[train.apply(lambda x: "?" in list(x), axis=1)]

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
4,4,24,Private,122234,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,20,?,0
11,11,21,?,204226,Some-college,10,Never-married,?,Unmarried,White,Female,0,0,35,United-States,0
30,30,20,?,202994,Some-college,10,Never-married,?,Own-child,White,Female,0,0,16,United-States,0
34,34,31,?,505438,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,30,Mexico,0
66,66,67,?,39100,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,0,0,5,United-States,0
67,67,65,?,404601,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,2414,0,30,United-States,0
74,74,19,?,218471,HS-grad,9,Never-married,?,Own-child,White,Female,0,1602,30,United-States,0
103,103,34,?,146589,HS-grad,9,Never-married,?,Unmarried,Black,Female,0,0,40,United-States,0
125,125,21,?,123983,Some-college,10,Never-married,?,Other-relative,Asian-Pac-Islander,Male,0,0,10,Vietnam,0
130,130,20,?,124242,Some-college,10,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
133,133,36,Private,150601,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,?,0
134,134,48,?,174533,11th,7,Separated,?,Unmarried,White,Male,0,0,40,United-States,0
138,138,23,Private,184400,10th,6,Never-married,Transport-moving,Own-child,Asian-Pac-Islander,Male,0,0,30,?,0
145,145,25,?,214925,10th,6,Never-married,?,Own-child,Black,Male,0,0,40,United-States,0
147,147,60,?,106282,9th,5,Widowed,?,Not-in-family,White,Female,0,0,40,United-States,0
160,160,28,Private,309620,Some-college,10,Married-civ-spouse,Sales,Husband,Other,Male,0,0,60,?,0
172,172,45,Private,480717,Bachelors,13,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,38,?,0
176,176,37,Private,245482,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
187,187,18,?,151463,11th,7,Never-married,?,Other-relative,White,Male,0,0,7,United-States,0
189,189,72,?,108796,Prof-school,15,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,1
201,201,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,?,0
218,218,42,Self-emp-not-inc,115323,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,7,?,0
220,220,24,?,172152,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,0,0,25,Taiwan,0
227,227,24,?,151153,Some-college,10,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,99999,0,50,South,1
229,229,76,?,79445,10th,6,Married-civ-spouse,?,Husband,White,Male,1173,0,40,United-States,0
232,232,63,?,146196,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
235,235,74,?,33114,10th,6,Married-civ-spouse,?,Husband,Amer-Indian-Eskimo,Male,1797,0,30,United-States,0
236,236,34,?,93834,HS-grad,9,Separated,?,Own-child,White,Female,0,0,8,United-States,0
247,247,42,?,204817,9th,5,Never-married,?,Own-child,Black,Male,0,0,35,United-States,0
266,266,42,Private,92288,Masters,14,Married-civ-spouse,Sales,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25689,25689,18,?,128538,Some-college,10,Never-married,?,Own-child,White,Female,0,0,6,United-States,0
25724,25724,32,Private,209317,HS-grad,9,Separated,Exec-managerial,Not-in-family,White,Male,0,0,40,?,0
25745,25745,47,?,34458,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,0
25755,25755,42,Private,337629,12th,8,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,60,?,1
25761,25761,32,Private,178623,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Female,0,0,40,?,0
25767,25767,24,?,390608,HS-grad,9,Never-married,?,Not-in-family,White,Female,0,0,36,United-States,0
25769,25769,35,?,374716,9th,5,Married-civ-spouse,?,Wife,White,Female,0,0,35,United-States,0
25773,25773,60,?,191118,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,1848,40,United-States,1
25791,25791,26,Private,359327,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,?,0
25797,25797,36,?,224886,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
25807,25807,46,Private,126513,HS-grad,9,Separated,Craft-repair,Unmarried,Black,Female,0,0,40,?,0
25855,25855,22,?,219233,HS-grad,9,Never-married,?,Own-child,Black,Male,0,1602,30,United-States,0
25870,25870,37,Private,130620,12th,8,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,0,33,?,0
25878,25878,19,?,351195,9th,5,Never-married,?,Other-relative,White,Male,0,1719,35,El-Salvador,0
25879,25879,66,?,212759,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,6767,0,20,United-States,0
25883,25883,20,?,150084,HS-grad,9,Never-married,?,Own-child,White,Male,0,0,25,United-States,0
25886,25886,19,?,185619,Some-college,10,Never-married,?,Own-child,White,Female,0,0,20,United-States,0
25895,25895,27,Private,104457,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Male,0,0,40,?,0
25908,25908,55,Private,196126,Bachelors,13,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,?,0
25914,25914,40,?,180362,Bachelors,13,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
25933,25933,64,?,196288,Assoc-acdm,12,Never-married,?,Not-in-family,White,Female,0,0,20,United-States,0
25937,25937,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,0
25944,25944,34,?,268127,12th,8,Separated,?,Unmarried,Black,Female,0,0,40,United-States,0
25980,25980,17,?,112942,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25991,25991,35,?,117528,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,1
26009,26009,73,?,89852,1st-4th,2,Married-civ-spouse,?,Husband,White,Male,0,0,40,Portugal,0
26010,26010,63,?,321403,9th,5,Separated,?,Not-in-family,Black,Male,0,0,40,United-States,0
26012,26012,36,?,214896,9th,5,Divorced,?,Unmarried,White,Female,0,0,40,Mexico,0
26046,26046,78,?,165694,Masters,14,Widowed,?,Not-in-family,White,Female,0,0,15,United-States,0
26048,26048,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0

train.age.plot(kind='kde')

In [18]:
train.age.plot(kind='box')

### 2.DATA Preprocessing

2.1 결측치 처리

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26049 entries, 0 to 26048
Data columns (total 16 columns):
id                26049 non-null int64
age               26049 non-null int64
workclass         26049 non-null object
fnlwgt            26049 non-null int64
education         26049 non-null object
education_num     26049 non-null int64
marital_status    26049 non-null object
occupation        26049 non-null object
relationship      26049 non-null object
race              26049 non-null object
sex               26049 non-null object
capital_gain      26049 non-null int64
capital_loss      26049 non-null int64
hours_per_week    26049 non-null int64
native_country    26049 non-null object
income            26049 non-null int64
dtypes: int64(8), object(8)
memory usage: 3.2+ MB

In [20]:
train[train.apply(lambda x: "?" in list(x), axis=1)]
#피처에 ?가있으면 false or true

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
4,4,24,Private,122234,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,20,?,0
11,11,21,?,204226,Some-college,10,Never-married,?,Unmarried,White,Female,0,0,35,United-States,0
30,30,20,?,202994,Some-college,10,Never-married,?,Own-child,White,Female,0,0,16,United-States,0
34,34,31,?,505438,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,30,Mexico,0
66,66,67,?,39100,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,0,0,5,United-States,0
67,67,65,?,404601,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,2414,0,30,United-States,0
74,74,19,?,218471,HS-grad,9,Never-married,?,Own-child,White,Female,0,1602,30,United-States,0
103,103,34,?,146589,HS-grad,9,Never-married,?,Unmarried,Black,Female,0,0,40,United-States,0
125,125,21,?,123983,Some-college,10,Never-married,?,Other-relative,Asian-Pac-Islander,Male,0,0,10,Vietnam,0
130,130,20,?,124242,Some-college,10,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
133,133,36,Private,150601,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,?,0
134,134,48,?,174533,11th,7,Separated,?,Unmarried,White,Male,0,0,40,United-States,0
138,138,23,Private,184400,10th,6,Never-married,Transport-moving,Own-child,Asian-Pac-Islander,Male,0,0,30,?,0
145,145,25,?,214925,10th,6,Never-married,?,Own-child,Black,Male,0,0,40,United-States,0
147,147,60,?,106282,9th,5,Widowed,?,Not-in-family,White,Female,0,0,40,United-States,0
160,160,28,Private,309620,Some-college,10,Married-civ-spouse,Sales,Husband,Other,Male,0,0,60,?,0
172,172,45,Private,480717,Bachelors,13,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,38,?,0
176,176,37,Private,245482,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
187,187,18,?,151463,11th,7,Never-married,?,Other-relative,White,Male,0,0,7,United-States,0
189,189,72,?,108796,Prof-school,15,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,1
201,201,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,?,0
218,218,42,Self-emp-not-inc,115323,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,7,?,0
220,220,24,?,172152,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,0,0,25,Taiwan,0
227,227,24,?,151153,Some-college,10,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,99999,0,50,South,1
229,229,76,?,79445,10th,6,Married-civ-spouse,?,Husband,White,Male,1173,0,40,United-States,0
232,232,63,?,146196,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
235,235,74,?,33114,10th,6,Married-civ-spouse,?,Husband,Amer-Indian-Eskimo,Male,1797,0,30,United-States,0
236,236,34,?,93834,HS-grad,9,Separated,?,Own-child,White,Female,0,0,8,United-States,0
247,247,42,?,204817,9th,5,Never-married,?,Own-child,Black,Male,0,0,35,United-States,0
266,266,42,Private,92288,Masters,14,Married-civ-spouse,Sales,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25689,25689,18,?,128538,Some-college,10,Never-married,?,Own-child,White,Female,0,0,6,United-States,0
25724,25724,32,Private,209317,HS-grad,9,Separated,Exec-managerial,Not-in-family,White,Male,0,0,40,?,0
25745,25745,47,?,34458,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,0
25755,25755,42,Private,337629,12th,8,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,60,?,1
25761,25761,32,Private,178623,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Female,0,0,40,?,0
25767,25767,24,?,390608,HS-grad,9,Never-married,?,Not-in-family,White,Female,0,0,36,United-States,0
25769,25769,35,?,374716,9th,5,Married-civ-spouse,?,Wife,White,Female,0,0,35,United-States,0
25773,25773,60,?,191118,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,1848,40,United-States,1
25791,25791,26,Private,359327,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,?,0
25797,25797,36,?,224886,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
25807,25807,46,Private,126513,HS-grad,9,Separated,Craft-repair,Unmarried,Black,Female,0,0,40,?,0
25855,25855,22,?,219233,HS-grad,9,Never-married,?,Own-child,Black,Male,0,1602,30,United-States,0
25870,25870,37,Private,130620,12th,8,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,0,33,?,0
25878,25878,19,?,351195,9th,5,Never-married,?,Other-relative,White,Male,0,1719,35,El-Salvador,0
25879,25879,66,?,212759,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,6767,0,20,United-States,0
25883,25883,20,?,150084,HS-grad,9,Never-married,?,Own-child,White,Male,0,0,25,United-States,0
25886,25886,19,?,185619,Some-college,10,Never-married,?,Own-child,White,Female,0,0,20,United-States,0
25895,25895,27,Private,104457,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Male,0,0,40,?,0
25908,25908,55,Private,196126,Bachelors,13,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,?,0
25914,25914,40,?,180362,Bachelors,13,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
25933,25933,64,?,196288,Assoc-acdm,12,Never-married,?,Not-in-family,White,Female,0,0,20,United-States,0
25937,25937,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,0
25944,25944,34,?,268127,12th,8,Separated,?,Unmarried,Black,Female,0,0,40,United-States,0
25980,25980,17,?,112942,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25991,25991,35,?,117528,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,1
26009,26009,73,?,89852,1st-4th,2,Married-civ-spouse,?,Husband,White,Male,0,0,40,Portugal,0
26010,26010,63,?,321403,9th,5,Separated,?,Not-in-family,Black,Male,0,0,40,United-States,0
26012,26012,36,?,214896,9th,5,Divorced,?,Unmarried,White,Female,0,0,40,Mexico,0
26046,26046,78,?,165694,Masters,14,Widowed,?,Not-in-family,White,Female,0,0,15,United-States,0
26048,26048,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0

In [21]:
train[train.apply(lambda x: "?" in list(x), axis=1)]

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
4,4,24,Private,122234,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,20,?,0
11,11,21,?,204226,Some-college,10,Never-married,?,Unmarried,White,Female,0,0,35,United-States,0
30,30,20,?,202994,Some-college,10,Never-married,?,Own-child,White,Female,0,0,16,United-States,0
34,34,31,?,505438,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,30,Mexico,0
66,66,67,?,39100,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,0,0,5,United-States,0
67,67,65,?,404601,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,2414,0,30,United-States,0
74,74,19,?,218471,HS-grad,9,Never-married,?,Own-child,White,Female,0,1602,30,United-States,0
103,103,34,?,146589,HS-grad,9,Never-married,?,Unmarried,Black,Female,0,0,40,United-States,0
125,125,21,?,123983,Some-college,10,Never-married,?,Other-relative,Asian-Pac-Islander,Male,0,0,10,Vietnam,0
130,130,20,?,124242,Some-college,10,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
133,133,36,Private,150601,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,?,0
134,134,48,?,174533,11th,7,Separated,?,Unmarried,White,Male,0,0,40,United-States,0
138,138,23,Private,184400,10th,6,Never-married,Transport-moving,Own-child,Asian-Pac-Islander,Male,0,0,30,?,0
145,145,25,?,214925,10th,6,Never-married,?,Own-child,Black,Male,0,0,40,United-States,0
147,147,60,?,106282,9th,5,Widowed,?,Not-in-family,White,Female,0,0,40,United-States,0
160,160,28,Private,309620,Some-college,10,Married-civ-spouse,Sales,Husband,Other,Male,0,0,60,?,0
172,172,45,Private,480717,Bachelors,13,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,38,?,0
176,176,37,Private,245482,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
187,187,18,?,151463,11th,7,Never-married,?,Other-relative,White,Male,0,0,7,United-States,0
189,189,72,?,108796,Prof-school,15,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,1
201,201,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,?,0
218,218,42,Self-emp-not-inc,115323,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,7,?,0
220,220,24,?,172152,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,0,0,25,Taiwan,0
227,227,24,?,151153,Some-college,10,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,99999,0,50,South,1
229,229,76,?,79445,10th,6,Married-civ-spouse,?,Husband,White,Male,1173,0,40,United-States,0
232,232,63,?,146196,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
235,235,74,?,33114,10th,6,Married-civ-spouse,?,Husband,Amer-Indian-Eskimo,Male,1797,0,30,United-States,0
236,236,34,?,93834,HS-grad,9,Separated,?,Own-child,White,Female,0,0,8,United-States,0
247,247,42,?,204817,9th,5,Never-married,?,Own-child,Black,Male,0,0,35,United-States,0
266,266,42,Private,92288,Masters,14,Married-civ-spouse,Sales,Husband,Asian-Pac-Islander,Male,0,0,40,?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25689,25689,18,?,128538,Some-college,10,Never-married,?,Own-child,White,Female,0,0,6,United-States,0
25724,25724,32,Private,209317,HS-grad,9,Separated,Exec-managerial,Not-in-family,White,Male,0,0,40,?,0
25745,25745,47,?,34458,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,0
25755,25755,42,Private,337629,12th,8,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,60,?,1
25761,25761,32,Private,178623,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Female,0,0,40,?,0
25767,25767,24,?,390608,HS-grad,9,Never-married,?,Not-in-family,White,Female,0,0,36,United-States,0
25769,25769,35,?,374716,9th,5,Married-civ-spouse,?,Wife,White,Female,0,0,35,United-States,0
25773,25773,60,?,191118,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,1848,40,United-States,1
25791,25791,26,Private,359327,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,?,0
25797,25797,36,?,224886,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
25807,25807,46,Private,126513,HS-grad,9,Separated,Craft-repair,Unmarried,Black,Female,0,0,40,?,0
25855,25855,22,?,219233,HS-grad,9,Never-married,?,Own-child,Black,Male,0,1602,30,United-States,0
25870,25870,37,Private,130620,12th,8,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,0,33,?,0
25878,25878,19,?,351195,9th,5,Never-married,?,Other-relative,White,Male,0,1719,35,El-Salvador,0
25879,25879,66,?,212759,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,6767,0,20,United-States,0
25883,25883,20,?,150084,HS-grad,9,Never-married,?,Own-child,White,Male,0,0,25,United-States,0
25886,25886,19,?,185619,Some-college,10,Never-married,?,Own-child,White,Female,0,0,20,United-States,0
25895,25895,27,Private,104457,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Male,0,0,40,?,0
25908,25908,55,Private,196126,Bachelors,13,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,?,0
25914,25914,40,?,180362,Bachelors,13,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
25933,25933,64,?,196288,Assoc-acdm,12,Never-married,?,Not-in-family,White,Female,0,0,20,United-States,0
25937,25937,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,0
25944,25944,34,?,268127,12th,8,Separated,?,Unmarried,Black,Female,0,0,40,United-States,0
25980,25980,17,?,112942,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25991,25991,35,?,117528,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,1
26009,26009,73,?,89852,1st-4th,2,Married-civ-spouse,?,Husband,White,Male,0,0,40,Portugal,0
26010,26010,63,?,321403,9th,5,Separated,?,Not-in-family,Black,Male,0,0,40,United-States,0
26012,26012,36,?,214896,9th,5,Divorced,?,Unmarried,White,Female,0,0,40,Mexico,0
26046,26046,78,?,165694,Masters,14,Widowed,?,Not-in-family,White,Female,0,0,15,United-States,0
26048,26048,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0

In [22]:
train.workclass.value_counts()

Private             18123
Self-emp-not-inc     2030
Local-gov            1692
?                    1502
State-gov            1043
Self-emp-inc          877
Federal-gov           765
Without-pay            11
Never-worked            6
Name: workclass, dtype: int64

In [23]:
train.occupation.value_counts()

Prof-specialty       3304
Craft-repair         3262
Exec-managerial      3246
Sales                2998
Adm-clerical         2983
Other-service        2626
Machine-op-inspct    1582
?                    1508
Transport-moving     1270
Handlers-cleaners    1092
Farming-fishing       784
Tech-support          742
Protective-serv       522
Priv-house-serv       123
Armed-Forces            7
Name: occupation, dtype: int64

### 결측치 처리

삭제할 것인지, 대치할 것인지

In [24]:
train[(train['workclass'] == '?')&(train['occupation'] == '?')]
#test데이터에서는 다를 수도 있음 
#income을 보면 확인, ?는 never worked라고 예측

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
11,11,21,?,204226,Some-college,10,Never-married,?,Unmarried,White,Female,0,0,35,United-States,0
30,30,20,?,202994,Some-college,10,Never-married,?,Own-child,White,Female,0,0,16,United-States,0
34,34,31,?,505438,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,30,Mexico,0
66,66,67,?,39100,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,0,0,5,United-States,0
67,67,65,?,404601,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,2414,0,30,United-States,0
74,74,19,?,218471,HS-grad,9,Never-married,?,Own-child,White,Female,0,1602,30,United-States,0
103,103,34,?,146589,HS-grad,9,Never-married,?,Unmarried,Black,Female,0,0,40,United-States,0
125,125,21,?,123983,Some-college,10,Never-married,?,Other-relative,Asian-Pac-Islander,Male,0,0,10,Vietnam,0
130,130,20,?,124242,Some-college,10,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
134,134,48,?,174533,11th,7,Separated,?,Unmarried,White,Male,0,0,40,United-States,0
145,145,25,?,214925,10th,6,Never-married,?,Own-child,Black,Male,0,0,40,United-States,0
147,147,60,?,106282,9th,5,Widowed,?,Not-in-family,White,Female,0,0,40,United-States,0
187,187,18,?,151463,11th,7,Never-married,?,Other-relative,White,Male,0,0,7,United-States,0
189,189,72,?,108796,Prof-school,15,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,1
220,220,24,?,172152,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,0,0,25,Taiwan,0
227,227,24,?,151153,Some-college,10,Never-married,?,Not-in-family,Asian-Pac-Islander,Male,99999,0,50,South,1
229,229,76,?,79445,10th,6,Married-civ-spouse,?,Husband,White,Male,1173,0,40,United-States,0
232,232,63,?,146196,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
235,235,74,?,33114,10th,6,Married-civ-spouse,?,Husband,Amer-Indian-Eskimo,Male,1797,0,30,United-States,0
236,236,34,?,93834,HS-grad,9,Separated,?,Own-child,White,Female,0,0,8,United-States,0
247,247,42,?,204817,9th,5,Never-married,?,Own-child,Black,Male,0,0,35,United-States,0
270,270,30,?,164940,HS-grad,9,Separated,?,Unmarried,Black,Female,0,0,25,United-States,0
271,271,81,?,162882,HS-grad,9,Divorced,?,Not-in-family,White,Female,0,0,35,United-States,0
338,338,71,?,205011,Some-college,10,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,0
346,346,58,?,361870,HS-grad,9,Married-civ-spouse,?,Husband,Black,Male,0,0,30,United-States,0
350,350,32,?,981628,HS-grad,9,Divorced,?,Unmarried,Black,Male,0,0,40,United-States,0
352,352,61,?,232618,Prof-school,15,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,1
361,361,43,?,82077,Some-college,10,Divorced,?,Unmarried,Asian-Pac-Islander,Female,0,0,40,United-States,0
368,368,41,?,149385,HS-grad,9,Never-married,?,Not-in-family,White,Female,0,0,30,United-States,0
370,370,22,?,199426,Some-college,10,Never-married,?,Not-in-family,White,Female,0,0,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25513,25513,19,?,128453,HS-grad,9,Never-married,?,Own-child,White,Female,0,0,28,United-States,0
25532,25532,19,?,225775,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25548,25548,56,?,128900,Some-college,10,Widowed,?,Not-in-family,Black,Female,0,0,40,United-States,0
25624,25624,18,?,395567,11th,7,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25628,25628,24,?,256240,7th-8th,4,Married-civ-spouse,?,Own-child,White,Male,0,0,60,United-States,0
25640,25640,32,?,115745,Some-college,10,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
25647,25647,68,?,140282,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,8,United-States,0
25685,25685,19,?,291509,12th,8,Never-married,?,Own-child,White,Male,0,0,28,United-States,0
25689,25689,18,?,128538,Some-college,10,Never-married,?,Own-child,White,Female,0,0,6,United-States,0
25745,25745,47,?,34458,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,0
25767,25767,24,?,390608,HS-grad,9,Never-married,?,Not-in-family,White,Female,0,0,36,United-States,0
25769,25769,35,?,374716,9th,5,Married-civ-spouse,?,Wife,White,Female,0,0,35,United-States,0
25773,25773,60,?,191118,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,1848,40,United-States,1
25797,25797,36,?,224886,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,0
25855,25855,22,?,219233,HS-grad,9,Never-married,?,Own-child,Black,Male,0,1602,30,United-States,0
25878,25878,19,?,351195,9th,5,Never-married,?,Other-relative,White,Male,0,1719,35,El-Salvador,0
25879,25879,66,?,212759,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,6767,0,20,United-States,0
25883,25883,20,?,150084,HS-grad,9,Never-married,?,Own-child,White,Male,0,0,25,United-States,0
25886,25886,19,?,185619,Some-college,10,Never-married,?,Own-child,White,Female,0,0,20,United-States,0
25914,25914,40,?,180362,Bachelors,13,Never-married,?,Own-child,White,Female,0,0,40,United-States,0
25933,25933,64,?,196288,Assoc-acdm,12,Never-married,?,Not-in-family,White,Female,0,0,20,United-States,0
25937,25937,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,0
25944,25944,34,?,268127,12th,8,Separated,?,Unmarried,Black,Female,0,0,40,United-States,0
25980,25980,17,?,112942,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,0
25991,25991,35,?,117528,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,1
26009,26009,73,?,89852,1st-4th,2,Married-civ-spouse,?,Husband,White,Male,0,0,40,Portugal,0
26010,26010,63,?,321403,9th,5,Separated,?,Not-in-family,Black,Male,0,0,40,United-States,0
26012,26012,36,?,214896,9th,5,Divorced,?,Unmarried,White,Female,0,0,40,Mexico,0
26046,26046,78,?,165694,Masters,14,Widowed,?,Not-in-family,White,Female,0,0,15,United-States,0
26048,26048,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0

In [25]:
train.native_country.value_counts()
#'?'에러?,미기입?

United-States                 23371
Mexico                          534
?                               456
Philippines                     163
Germany                         101
Puerto-Rico                      95
Canada                           92
El-Salvador                      79
India                            77
Cuba                             76
England                          67
Jamaica                          64
South                            63
China                            57
Guatemala                        52
Columbia                         52
Italy                            50
Vietnam                          50
Dominican-Republic               48
Japan                            47
Poland                           47
Taiwan                           39
Iran                             35
Haiti                            35
Portugal                         30
Nicaragua                        28
Peru                             26
Greece                           24
Ecuador                          24
France                           24
Ireland                          18
Laos                             15
Cambodia                         14
Hong                             14
Trinadad&Tobago                  14
Outlying-US(Guam-USVI-etc)       13
Thailand                         13
Yugoslavia                       12
Hungary                          11
Honduras                         11
Scotland                          8
Name: native_country, dtype: int64

In [26]:
train.loc[(train.age >= 30)&(train.workclass=='?'), 'workclass'] = 'No'
#age가 30이 넘고, workclass의 값이 ?인 변수는 workclass의 값을 'No'로 정의

In [27]:
train.workclass.value_counts()

Private             18123
Self-emp-not-inc     2030
Local-gov            1692
State-gov            1043
Self-emp-inc          877
No                    868
Federal-gov           765
?                     634
Without-pay            11
Never-worked            6
Name: workclass, dtype: int64

### Null check 관련 팁
데이터를 일일이 다 확인하지 않고 결측치가 있는지 확인하는 방법

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26049 entries, 0 to 26048
Data columns (total 16 columns):
id                26049 non-null int64
age               26049 non-null int64
workclass         26049 non-null object
fnlwgt            26049 non-null int64
education         26049 non-null object
education_num     26049 non-null int64
marital_status    26049 non-null object
occupation        26049 non-null object
relationship      26049 non-null object
race              26049 non-null object
sex               26049 non-null object
capital_gain      26049 non-null int64
capital_loss      26049 non-null int64
hours_per_week    26049 non-null int64
native_country    26049 non-null object
income            26049 non-null int64
dtypes: int64(8), object(8)
memory usage: 3.2+ MB

null값이 있는 data type는 'plot'

In [29]:
a=2/7

In [30]:
f"a값은 {a:.2f}입니다"

'a값은 0.29입니다'

### 2.2 이상치 처리
수치형 데이터에 이상한 값이 없는지 한번 확인

In [31]:
train.describe()

,id,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income
count,26049.000000,26049.000000,2.604900e+04,26049.000000,26049.00000,26049.000000,26049.000000,26049.000000
mean,13024.000000,38.569235,1.903045e+05,10.088372,1087.68970,87.732734,40.443126,0.242044
std,7519.842917,13.671489,1.059663e+05,2.567610,7388.85469,403.230205,12.361850,0.428329
min,0.000000,17.000000,1.376900e+04,1.000000,0.00000,0.000000,1.000000,0.000000
25%,6512.000000,28.000000,1.181080e+05,9.000000,0.00000,0.000000,40.000000,0.000000
50%,13024.000000,37.000000,1.788660e+05,10.000000,0.00000,0.000000,40.000000,0.000000
75%,19536.000000,48.000000,2.377350e+05,12.000000,0.00000,0.000000,45.000000,0.000000
max,26048.000000,90.000000,1.484705e+06,16.000000,99999.00000,4356.000000,99.000000,1.000000

In [32]:
train.loc[train.capital_gain < 99999].sort_values('capital_gain', ascending=False)

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
13280,13280,27,Private,211032,Preschool,1,Married-civ-spouse,Farming-fishing,Other-relative,White,Male,41310,0,24,Mexico,0
12625,12625,19,Private,188815,HS-grad,9,Never-married,Other-service,Own-child,White,Female,34095,0,20,United-States,0
2893,2893,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,0
17707,17707,20,?,273701,Some-college,10,Never-married,?,Other-relative,Black,Male,34095,0,10,United-States,0
4703,4703,55,Self-emp-not-inc,145574,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,34095,0,60,United-States,0
11819,11819,58,Self-emp-inc,112945,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,27828,0,40,United-States,1
8722,8722,37,Private,116358,HS-grad,9,Never-married,Craft-repair,Other-relative,Amer-Indian-Eskimo,Male,27828,0,48,United-States,1
4557,4557,37,Self-emp-not-inc,32239,HS-grad,9,Divorced,Farming-fishing,Not-in-family,White,Male,27828,0,40,United-States,1
11674,11674,35,Private,202027,Bachelors,13,Divorced,Exec-managerial,Not-in-family,White,Male,27828,0,50,United-States,1
7761,7761,58,No,353244,Bachelors,13,Widowed,?,Unmarried,White,Female,27828,0,50,United-States,1
6878,6878,36,Self-emp-inc,184456,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Male,27828,0,55,United-States,1
23296,23296,41,Private,106679,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Male,27828,0,50,United-States,1
8036,8036,30,Private,116138,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,27828,0,60,United-States,1
24158,24158,59,Private,154100,Masters,14,Never-married,Sales,Not-in-family,White,Female,27828,0,45,United-States,1
15422,15422,53,Self-emp-not-inc,137547,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,27828,0,40,Philippines,1
26002,26002,47,Self-emp-inc,79627,Prof-school,15,Divorced,Prof-specialty,Not-in-family,White,Male,27828,0,50,United-States,1
22869,22869,51,Private,673764,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,27828,0,40,United-States,1
14236,14236,25,Private,169905,Assoc-voc,11,Never-married,Sales,Not-in-family,White,Male,27828,0,40,United-States,1
6140,6140,41,Private,182108,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,27828,0,35,United-States,1
10686,10686,54,Self-emp-not-inc,28186,Bachelors,13,Divorced,Farming-fishing,Not-in-family,White,Male,27828,0,50,United-States,1
21872,21872,64,Private,66634,Bachelors,13,Divorced,Exec-managerial,Unmarried,White,Male,27828,0,50,United-States,1
9750,9750,46,Private,133938,Masters,14,Divorced,Exec-managerial,Not-in-family,White,Female,27828,0,50,United-States,1
15797,15797,47,Private,304857,Masters,14,Separated,Tech-support,Not-in-family,White,Male,27828,0,40,United-States,1
22478,22478,36,Private,329980,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,27828,0,40,United-States,1
13354,13354,49,Private,120629,Bachelors,13,Divorced,Exec-managerial,Not-in-family,Black,Female,27828,0,60,United-States,1
19340,19340,47,Private,233511,Masters,14,Divorced,Sales,Not-in-family,White,Male,27828,0,60,United-States,1
11368,11368,45,Private,148549,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,27828,0,56,United-States,1
24030,24030,29,Private,82242,Prof-school,15,Never-married,Prof-specialty,Unmarried,White,Male,27828,0,45,Germany,1
4980,4980,37,Private,109133,Masters,14,Separated,Exec-managerial,Not-in-family,White,Male,27828,0,60,Iran,1
16033,16033,36,Private,184456,Prof-school,15,Never-married,Exec-managerial,Not-in-family,White,Male,27828,0,50,United-States,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9024,9024,39,Private,297449,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,1
9023,9023,24,Private,205844,Bachelors,13,Never-married,Exec-managerial,Own-child,Black,Female,0,0,40,United-States,0
9022,9022,21,Private,148444,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,25,United-States,0
9021,9021,60,Private,75726,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Female,0,1092,40,United-States,0
9020,9020,64,Private,169482,Some-college,10,Married-spouse-absent,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,0
9040,9040,18,Private,280603,11th,7,Never-married,Sales,Own-child,White,Female,0,0,30,United-States,0
9042,9042,38,Private,34996,Some-college,10,Separated,Other-service,Unmarried,White,Female,0,0,40,United-States,0
9066,9066,62,Self-emp-not-inc,197353,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1740,40,United-States,0
9056,9056,19,Private,199495,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,0
9065,9065,35,Private,187053,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Female,0,0,60,United-States,1
9064,9064,51,Private,178241,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,0,0,40,United-States,1
9063,9063,54,Private,189607,Bachelors,13,Never-married,Other-service,Own-child,Black,Female,0,0,36,United-States,0
9062,9062,35,State-gov,349066,HS-grad,9,Divorced,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,0
9061,9061,46,Private,175109,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,1485,40,United-States,1
9060,9060,20,?,346341,Some-college,10,Never-married,?,Not-in-family,White,Female,0,0,35,United-States,0
9059,9059,30,Private,170130,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
9058,9058,25,Private,289980,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,35,United-States,0
9057,9057,27,Local-gov,163862,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,60,United-States,0
9054,9054,30,Federal-gov,423064,HS-grad,9,Separated,Adm-clerical,Other-relative,Black,Male,0,0,35,United-States,0
9043,9043,37,Private,61778,Bachelors,13,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,30,United-States,0
9052,9052,32,Private,152109,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,48,United-States,0
9051,9051,38,Private,99233,Prof-school,15,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,1
9050,9050,47,Private,175990,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,30,United-States,1
9049,9049,29,Private,52199,HS-grad,9,Married-spouse-absent,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,0
9048,9048,57,Federal-gov,337895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,40,United-States,1
9047,9047,48,Private,180446,10th,6,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,0,0,40,United-States,0
9046,9046,28,Private,273269,Some-college,10,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,40,United-States,0
9045,9045,36,Self-emp-not-inc,34180,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,70,United-States,1
9044,9044,23,?,283806,9th,5,Divorced,?,Not-in-family,White,Female,0,0,35,United-States,0
26048,26048,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0

### log 표현

In [35]:
train["log_capital_gain"] = train.capital_gain.map(lambda x: np.log(x, where=(x!=0)))

In [36]:
train[['capital_gain', 'log_capital_gain']].describe()

       capital_gain  log_capital_gain
count   26049.00000      26049.000000
mean     1087.68970        987.677568
std      7388.85469       7017.485308
min         0.00000          0.000000
25%         0.00000          0.000000
50%         0.00000          0.000000
75%         0.00000          0.000000
max     99999.00000      99999.000000